name: Deploy Laravel via SSH

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Deploy via SSH
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}         # La IP o DNS público de tu instancia
          EC2_USER: ${{ secrets.EC2_USER }}         # Usuario, ej. "ubuntu" o "ec2-user"
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Tu clave privada
        run: |
          # Guardar la clave privada en un archivo temporal
          echo "$EC2_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Ejecutar los comandos de despliegue en la instancia vía SSH
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /var/www/ECOMMERCE-BACK-LARAVEL
            git pull origin main
            composer install --no-dev --optimize-autoloader
            chmod -R 775 storage bootstrap/cache
            chown -R www-data:www-data storage bootstrap/cache
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            php artisan config:cache
            sudo systemctl restart php-fpm
            sudo systemctl restart nginx
            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart laravel:*
          EOF

          # Borrar la clave privada por seguridad
          rm -f private_key.pem
